#!/bin/sh -e

export DESTDIR="$1"

: >doc/meson.build

meson setup \
  -Dprefix=/usr \
  -Dbuildtype=release \
  -Dbackend-x11=disabled \
  -Dbackend-wayland=enabled \
  -Db_lto=true \
  . output

ninja -C output
ninja -C output install
