#!/bin/sh -e

export DESTDIR="$1"

:>doc/meson.build

for patch in *".patch"; do
    patch -p1<"$patch"
done

meson setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dbackend-x11=disabled \
    -Dbackend-wayland=enabled \
    -Dcore-plugins-as-shared-libraries=true \
    . output

ninja -C output
ninja -C output install
