#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

patch -p1 <musl-1.2.4.patch

autoreconf -fi

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --with-lz4

make
make DESTDIR="$1" install
