#!/bin/sh -e

export DESTDIR="$1"

install -Dm644 \
    libunwind/include/mach-o/compact_unwind_encoding.h \
    lld/include/mach-o/compact_unwind_encoding.h

cd lld
cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_INCLUDE_DIRS="/usr/include" \
    -Wno-dev

cmake --build   build
cmake --install build

ln -s lld "$1/usr/bin/ld"
