#!/bin/sh -e

export DESTDIR="$1"
hello
## no scdoc dep
sed '/subdir(.doc.)/d' meson.build >_
mv -f _ meson.build

meson \
    --prefix=/usr \
    -Denable-cairo=disabled \
    -Dpng-backend=libpng \
    -Dsvg-backend=none \
    . output

ninja -C output
ninja -C output install
