#!/bin/sh -e

# getconf, string and tar are provided by other packages
sed -e '/strings\\/d' \
    -e '/tar\\/d' \
    -e '/sha224sum\\/d' \
    -e '/sha384sum\\/d' \
    -e '/sha512-224sum\\/d' \
    -e '/sha512-256sum\\/d' Makefile > _
mv -f _ Makefile

make LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -static -fPIE"

mkdir -p "$1/usr/share/man"

make DESTDIR="$1" PREFIX=/usr install