#!/bin/sh -e

export DESTDIR="$1"

kiss l libwebp >/dev/null 2>/dev/null && webp=enabled || webp=disabled
kiss l giflib >/dev/null 2>/dev/null && giflib=enabled || giflib=disabled

meson setup \
    -Dauto-features=auto \
    -Dprefix=/usr \
    -Djpeg=enabled \
    -Dpng=enabled \
    -Dwebp="$webp" \
    -Dgif="$giflib" \
    . output

ninja -C output
ninja -C output install
