#!/bin/sh -e

( export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
    PERL_AUTOINSTALL=--skipdeps \
    PERL_MM_OPT="INSTALLDIR=vendor" \
    PERL_MB_OPT="--installdirs vendor" \
    MODULEBUILDRC=/dev/null

  perl Makefile.PL
    make
    make DESTDIR="$1" install
    find "$1" -name .packlist -o -name perllocal.pod -delete
)
