#!/bin/sh -e

#---------------------------------#
#          By  XDream8            #
#---------------------------------#
# this is not a normal package.   #
# it is more like a configuration #
#---------------------------------#

# functions

## $1: option
## $2: default value
## $3: value
change_opt() {
	sed "s/$1.*= $2/$1 = $3/g" config.def.h >_
	mv -f _ config.def.h
}

add_program_and_bind_it() {
	program_name="$1"
	program="$2"
	keybinding="$3"

	## add program_cmd
	sed "s#/\* commands \*/#/\* commands \*/\nstatic const char \*"$program_name"[] = { $(
		for i in $program; do
			printf '%s' "\"$i\","
		done
	) NULL };#g" config.def.h >_
	mv -f _ config.def.h

	## add keybinding
	sed "s#static const Key keys.* = {#static const Key keys[] = \{\n\t{ $keybinding, spawn, {.v = $program_name} },#g" config.def.h >_
	mv -f _ config.def.h
}

autostart() {
	program="$1"

	sed "s#static const char \*const autostart.* = {#static const char \*const autostart[] = {\n\t$(
		for cmd in $program; do
			printf '%s' "\"$cmd\","
		done
	) NULL,#g" config.def.h >_
	mv -f _ config.def.h
}

## apply patches
for patch in *".patch"; do
	[ -f "$patch" ] || continue
	## for debugging
	printf '%s\n' "applying patch: $patch"
	patch -p1 <"$patch"
done

## configuration

### change modkey
sed 's/#define MODKEY WLR_MODIFIER_ALT/#define MODKEY WLR_MODIFIER_LOGO/g' config.def.h >_
mv -f _ config.def.h

### if $LAUNCHER variable exists change launcher
if [ -n "$LAUNCHER" ]; then
	sed "s/\"wmenu-run\"/\"$LAUNCHER\"/g" config.def.h >_
	mv -f _ config.def.h
fi

### if $TERMINAL variable exists change launcher
if [ -n "$TERMINAL" ]; then
	sed "s/\"foot\"/\"$TERMINAL\"/g" config.def.h >_
	mv -f _ config.def.h
fi

### if $XKB_DEFAULT_LAYOUT variable is set, change default keyboard layout
if [ -n "$XKB_DEFAULT_LAYOUT" ]; then
	sed "s/.options = NULL,/.layout = \"$XKB_DEFAULT_LAYOUT\",\n.options = NULL,/g" config.def.h >_
	mv -f _ config.def.h
fi

### enable smartgaps
change_opt "smartgaps" "0" "1"
### repeat rate and delay
change_opt "repeat_rate" "25" "60"
change_opt "repeat_delay" "600" "300"
### set gap to 8
for gap in ih iv oh ov; do
	change_opt "gapp$gap" "10" "8"
done

### add programs
add_program_and_bind_it "librewolf_cmd" "librewolf" "MODKEY, XKB_KEY_w"
add_program_and_bind_it "emacs_cmd" "emacsclient -c" "MODKEY|WLR_MODIFIER_ALT, XKB_KEY_e"
add_program_and_bind_it "nnn_cmd" "footclient -T NNN -e nnn" "MODKEY|WLR_MODIFIER_ALT, XKB_KEY_r"
add_program_and_bind_it "htop_cmd" "footclient -T HTOP -e htop" "MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_R"
add_program_and_bind_it "alsamixer_cmd" "$HOME/.local/bin/scripts/alsamixer-open" "MODKEY|WLR_MODIFIER_ALT, XKB_KEY_a"
add_program_and_bind_it "browsermenu_cmd" "$HOME/.local/bin/scripts/browser-menu" "MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_W"
add_program_and_bind_it "configmenu_cmd" "$HOME/.local/bin/scripts/config-menu" "MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_E"

## autostart
autostart "foot --server"
autostart "wbg $HOME/defaults/Pictures/leaving_earth-wallpaper-1920x1080.jpg"
autostart "emacs --daemon"

cat config.def.h

## build
make
make DESTDIR="$1" PREFIX="/usr" install
