#!/bin/sh -e

patch -p1 <fix-glib.patch

# Remove fuse2 dependency (used solely with root "system-helper"
# daemon for file transfer. Unneeded in our case and drops the
# old fuse version.
# sed \
#     -e 's/as_fn_error.*fuse/: "/g' \
#     -e '/Werror=missing-include-dirs/d' configure > _
# mv -f _ configure

echo "int main(void) { return 1; }" > revokefs/main.c
:>revokefs/writer.c

PYTHONPATH=$PWD/pyparsing:$(python -c "import sys; print(':'.join(sys.path))")
export PYTHONPATH

sh ./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --sysconfdir=/etc \
    --with-system-bubblewrap \
    --enable-seccomp \
    --disable-system-helper \
    --disable-xauth \
    --disable-documentation \
    --without-systemd

make
make DESTDIR="$1" install
