#!/bin/sh -e

export DESTDIR="$1"

autoreconf -fi

sed '1s#/bin/sh#/bin/bash#' configure >_
mv -f _ configure
chmod +x configure

head -n 1 configure

./configure \
	--prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/bin \
	--disable-gc \
	--with-sandbox-shell=/usr/bin/busybox \
	--disable-tests \
	--disable-doc-gen

make
make install
