#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_X11=OFF \
    -DENABLE_OPENCV=OFF \
    -DENABLE_TURBOBASE64=OFF \
    -DENABLE_SWAY=ON \
    -Wno-dev

cmake --build   build
cmake --install build
