#!/bin/sh -e
# shellcheck disable=2016,2086

export CFLAGS="$CFLAGS -static"
export LDFLAGS="$LDFLAGS -static"

for patch in *".patch"; do
    patch -p1 <"$patch"
done

# disable debug and development flags to reduce bootloader size
truncate -s 0 mk/devel.mk

case "$(uname -m)" in
i686) targets="bios efi32" ;;
x86_64) targets="bios efi64" ;;
esac

make $targets installer

make INSTALLROOT="$1" SBINDIR=/usr/bin AUXDIR=/usr/lib/syslinux install

# Remove completely development stuff.
rm -rf "$1"/usr/lib/syslinux/com32/include "$1"/usr/lib/syslinux/com32/*.a
