#!/bin/sh -e

autoreconf -fi

./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make

install -Dm755 i3blocks "$1/usr/bin/i3blocks"
install -D docs/i3blocks.1 "$1/usr/share/man/man1/i3blocks.1"
