#!/bin/sh -e

for patch in *".patch"; do
    patch -p1 <"$patch"
done

## add support for fltk 1.4(development)
sed 's/1.3.\*/1.3.\*|1.4.\*/' configure.ac > _
mv -f _ configure.ac

autoreconf -fi

./configure \
    --prefix=/usr \
    --enable-gif \
    --enable-ipv6 \
    --enable-jpeg \
    --enable-png \
    --enable-ssl \
    --enable-threaded-dns

make
make DESTDIR="$1" install
